apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}