services:
  db:
    image: "mysql:8.0"
    container_name: wp_database
    restart: always
    env_file:
      - mysql.env
    volumes:
      - wp-db:/var/lib/mysql
    networks:
      - backend

  wordpress:
    image: "wordpress:latest"
    container_name: wordpress
    restart: always
    env_file:
      - wordpress.env
    volumes:
      - wp-data:/var/www/html
    networks:
      - backend
      - frontend

  proxy:
    image: nginx:alpine
    container_name: wp-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
      - db
    networks:
      - frontend

volumes:
  wp-db:
  wp-data:

networks:
  backend:
  frontend:
