apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.name}}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.wordpress.name}}
  type: NodePort
  ports:
    - port: {{ .Values.wordpress.port }}
      targetPort: {{ .Values.wordpress.port }}
      nodePort: {{ .Values.wordpress.nodePort }}